language: perl
perl:
  - "5.26-shrplib"
  - "5.24-shrplib"
  - "5.22-shrplib"
  - "5.20-shrplib"
  - "5.18-shrplib"
matrix:
  include:
    - perl: "5.18-shrplib"
      env: COVERAGE=1
  allow_failures:
    - perl: "blead"
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
